"""Phase-1 blueprint -> tau2 native Task. The domain-specific half (which
Task/EvaluationCriteria fields exist, how actions/outputs map) is delegated
to ``plugin.blueprint_to_native_task``; this module only adds the
domain-agnostic traceability metadata every plugin gets for free.
"""

from __future__ import annotations

from tau2.data_model.tasks import Description, Task

from apigen_mt.domains.base import DomainPlugin
from apigen_mt.phase1.schema import ValidatedTask


def blueprint_to_task(
    validated: ValidatedTask, plugin: DomainPlugin, task_id: str | None = None
) -> Task:
    task_id = task_id or validated.blueprint.blueprint_id
    task = plugin.blueprint_to_native_task(validated.blueprint, task_id)
    task.description = Description(
        purpose=validated.blueprint.thought,
        notes=(
            f"Generated by APIGen-MT. Committee aggregate={validated.committee.aggregate}/4, "
            f"retries={validated.retry_count}, source_blueprint_ids="
            f"{validated.blueprint.source_blueprint_ids or 'none'}."
        ),
    )
    return task
